CREATE TABLE teacher(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
email VARCHAR(255) UNIQUE NOT NULL,
birthday DATE NOT NULL,
specialties VARCHAR(255) UNIQUE NOT NULL,
turmaId INT NOT NULL
);