CREATE TABLE class(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
begin DATE NOT NULL,
finish DATE NOT NULL,
module INT NOT NULL,
studentId VARCHAR(255) NOT NULL,
teacherId VARCHAR(255) NOT NULL,
FOREIGN KEY (studentId ) REFERENCES student(id),
FOREIGN KEY (teacherId ) REFERENCES teacher(id)
);